### ISSUE TITLE
feeds do not update

### ISSUE THREAD

**Issue by voidplayer** [jparyani/Tiny-Tiny-RSS#14]
it shows this on the debug log:

**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Protocol not recognized.
    at server/hack-session.js:322:15
    at N (/node_modules/es6-promise.js:12:311)
    at new h (/node_modules/es6-promise.js:13:435)
    at HackSessionContextImpl.httpGet (server/hack-session.js:317:12)
    at ClientRequest.<anonymous> (server/hack-session.js:345:29)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at Socket.socketOnData (http.js:1639:20)
stack: 0x438ec0 0x41ae10 0x4194a0 0x402730 0x40303c 0x402953 0x4027cd 0x4b03b1
[17:28:36/79]     0.2344 (sec)
[17:28:36/79] Base feed: http://blog.wordtothewise.com/feed/
[17:28:36/79]  => 1970-01-01 00:00:00, 13 1
[17:28:38/79]     2.1132 (sec)
[17:28:38/79] Base feed: https://blog.sandstorm.io/feed.xml
[17:28:38/79]  => 1970-01-01 00:00:00, 14 1
[17:28:39/79]     0.2257 (sec)

restarting the grain does not fix it

**Comment by jparyani** [comment]
Hmm that's very weird, I'm not able to reproduce with those 2 feeds. Is there more to the log? Are you subscribed to more than those 2 feeds?

**Comment by voidplayer** [comment]
I rebooted the machine and its working now... but the uncaught exceptions keep showing... now im not sure if related to the feeds not updating tho :)

ex.

[22:14:36/84] Lock: update.lock
[22:14:36/84] marking all feeds as needing update...
[22:14:36/84] Scheduled 69 feeds to update...
[22:14:36/84] Base feed: http://blog.commandlinekungfu.com/feeds/posts/default
[22:14:36/84]  => 1970-01-01 00:00:00, 3 1
[22:14:36/84]     0.4569 (sec)
[22:14:36/84] Base feed: https://www.ibm.com/developerworks/views/linux/rss/libraryview.jsp
[22:14:36/84]  => 1970-01-01 00:00:00, 4 1
[22:14:37/84]     0.8369 (sec)
[22:14:37/84] Base feed: https://www.ibm.com/developerworks/views/opensource/rss/libraryview.jsp
[22:14:37/84]  => 1970-01-01 00:00:00, 5 1
[22:14:38/84]     0.8554 (sec)
[22:14:38/84] Base feed: http://l3net.wordpress.com/feed/
[22:14:38/84]  => 1970-01-01 00:00:00, 6 1
[22:14:39/84]     0.3771 (sec)
[22:14:39/84] Base feed: http://feeds.cyberciti.biz/Nixcraft-LinuxFreebsdSolarisTipsTricks
[22:14:39/84]  => 1970-01-01 00:00:00, 7 1
**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Status code 404 received in response.
    at ClientRequest.<anonymous> (server/hack-session.js:348:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at Socket.socketOnData (http.js:1639:20)
    at TCP.onread (net.js:528:27)
stack: 0x438ec0 0x41ae10 0x4194a0 0x402730 0x40303c 0x402953 0x4027cd 0x4b03b1
**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Status code 404 received in response.
    at ClientRequest.<anonymous> (server/hack-session.js:348:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at Socket.socketOnData (http.js:1639:20)
    at TCP.onread (net.js:528:27)
stack: 0x438ec0 0x41ae10 0x4194a0 0x402730 0x40303c 0x402953 0x4027cd 0x4b03b1
[22:14:39/84]     0.7459 (sec)
[22:14:39/84] Base feed: http://s3hh.wordpress.com/tag/lxc/feed/
[22:14:39/84]  => 1970-01-01 00:00:00, 8 1
[22:14:40/84]     0.6314 (sec)
[22:14:40/84] Base feed: http://systemadmin.es/feed
[22:14:40/84]  => 1970-01-01 00:00:00, 9 1
[22:14:40/84]     0.1226 (sec)
[22:14:40/84] Base feed: http://www.thegeekstuff.com/feed
[22:14:40/84]  => 1970-01-01 00:00:00, 10 1
[22:14:42/84]     1.8528 (sec)
[22:14:42/84] Base feed: http://administratosphere.wordpress.com/feed/
[22:14:42/84]  => 1970-01-01 00:00:00, 11 1
[22:14:42/84]     0.3375 (sec)
[22:14:42/84] Base feed: http://vimcasts.org/feeds/ogg
[22:14:42/84]  => 1970-01-01 00:00:00, 12 1
**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Protocol not recognized.
    at server/hack-session.js:322:15
    at N (/node_modules/es6-promise.js:12:311)
    at new h (/node_modules/es6-promise.js:13:435)
    at HackSessionContextImpl.httpGet (server/hack-session.js:317:12)
    at ClientRequest.<anonymous> (server/hack-session.js:345:29)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at Socket.socketOnData (http.js:1639:20)

**Comment by jparyani** [comment]
The 404s are reasonable (sadly one of the default feeds included in TinyTinyRss now 404s, so you'll see that error unless you remove the feed manually).

I'm still not able to see what's causing the `Protocol not recognized` error. It's raised in Sandstorm at https://github.com/sandstorm-io/sandstorm/blob/1231ed41a2182f7cd007ec4ea5f7238ad63be625/shell/server/hack-session.js#L322. My best guess is that it's some 3xx redirect that doesn't include http or https at the beginning, but I'm unable to track it down.

**Comment by voidplayer** [comment]
they should caught the exception and show a 404 on the logs... :(

Uncaught exception  and a backtrace reads pretty nasty on the logs

The protocol one does not show on logs that you can see from the web (probably because they show only the last few lines instead of everything), but Ive got a few more:

**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: socket hang up
    at createHangUpError (http.js:1528:15)
    at Socket.socketCloseListener (http.js:1578:23)
    at Socket.emit (events.js:117:20)

**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete](net.js:896:19)

okay, remote was too busy or something and the other one was down

but this one?

**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Status code 400 received in response.
    at ClientRequest.<anonymous> (server/hack-session.js:348:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at CleartextStream.socketOnData (http.js:1639:20)
    at CleartextStream.read [as _read](tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write](tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)

**\* Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: Error: Status code 403 received in response.
    at ClientRequest.<anonymous> (server/hack-session.js:348:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:152:23)
    at CleartextStream.socketOnData (http.js:1639:20)
    at CleartextStream.read [as _read](tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write](tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
